<?php

namespace MainBundle\Repository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumPhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPhotoAlbum($id)
    {
        $qb = $this ->createQueryBuilder('a');
        $qb ->where('a.album = :idAlbum')
            ->setParameter('idAlbum',$id);

        $resultat =$qb->getQuery() ;
        return $resultat->getResult();
    }
}
